### ISSUE TITLE
Jobs  Need to show notification message if no part time roles is not there

### ISSUE THREAD

**Issue by Raja8975** [null-open-security-community/swachalit#126]
Hi team,

When we select the part time opportunity in  Jobs page  it's not there .if we select full time or freelancer the notification is displayed as below " **AH! NO JOBS FOUND FOR THAT COMBINATION**!". if we select either parttime and full time notification message is displayed 
Steps to reproduce 
1.Goto  url (Job) "https://jobs.null.community/jobs/?location=&job_title="
2.Select "Full time" or "Freelancer" type Full time roles is displayed. if not message is displayed (AH! NO JOBS FOUND FOR THAT COMBINATION!) and search string is not displayed as "Parttime" in RHS
3.Select "Part time" no notification is displayed if vacancy is not there.

Actual result
No notification message(AH! NO JOBS FOUND FOR THAT COMBINATION!) is displayed.
Expected result
Notification message should be displayed if no such role is there 
Screenshot attached Please go through it
[Null_Ss.zip](https://github.com/null-open-security-community/swachalit/files/13060669/Null_Ss.zip)

Thanks

**Comment by anantshri** [comment]
@prashant3535 for null jobs.

closing here as null jobs is different project.
