### ISSUE TITLE
ui/ux improvements for community chapters page listing

### ISSUE THREAD

**Issue by sanjay7178** [null-open-security-community/swachalit#130]
@anantshri please check out i've made few improvements to chapters listing page  

Demo :

https://github.com/user-attachments/assets/19273364-dfe2-4fa3-a6ba-b3e67112dd09

related issue : https://github.com/null-open-security-community/swachalit/issues/128

**Comment by sanjay7178** [comment]
Added search chapter feature within chapters listing page 
Demo :

https://github.com/user-attachments/assets/ebbc49be-83dd-4f2d-8368-bb450b784fea

**Comment by anantshri** [comment]
@sanjay7178 this looks awesome, can you create a pull request with the changes.

**Comment by sanjay7178** [comment]
yeah , give me a while will make a pr

**Comment by sanjay7178** [comment]
@anantshri made the pr https://github.com/null-open-security-community/swachalit/pull/131 once review

**Comment by anantshri** [comment]
I have asked @abhisek for a review will wait 72 hours for his review otherwise will check and update.

**Comment by sanjay7178** [comment]
sure

**Comment by abhisek** [comment]
@anantshri The review & changes are completed. I have merged the PR. Can you trigger a release?

**Comment by sanjay7178** [comment]
Anything could i make contribute with this ? > @anantshri The review & changes are complete. I have merged the PR. Can you trigger a release?

**Comment by anantshri** [comment]
Release triggered this is live now. 

also closes #128
