### ISSUE TITLE
fix : razorpay form in mobile view of header and addition  of go to top button 

### ISSUE THREAD

**Issue by sanjay7178** [null-open-security-community/swachalit#134]
preview : 
- fix for razorpay form in mobile view
![image](https://github.com/user-attachments/assets/77d80791-244f-4748-8e57-192368215df9)
sub issue : #125 
- addition of go top button 
![image](https://github.com/user-attachments/assets/1605012d-01a3-4cc3-81a7-f19522bb6148)

@anantshri @abhisek

**Comment by abhisek** [comment]
Thanks @sanjay7178 This is merged.

@anantshri Can you please trigger a release?

**Comment by anantshri** [comment]
release done this is live now.
