### ISSUE TITLE
Aggregated Chapter Listing

### ISSUE THREAD

**Issue by abhisek** [null-open-security-community/swachalit#35]
Create an aggregated chapter listing page:
https://null.co.in/chapters

with

* Visual representation of chapters across India (+ global)
* List of active chapters

Examples:

https://developers.google.com/chart/interactive/docs/gallery/map
https://www.d3-graph-gallery.com/index.html

**Comment by avinashupadhya99** [comment]
@abhisek You can assign this to me. I will work on it.

**Comment by abhisek** [comment]
Done

**Comment by abhisek** [comment]
Hey @avinashupadhya99 

Any progress on this? Let me know if you need any assistance.

**Comment by abhisek** [comment]
Hi @avinashupadhya99 

Its in prod now.
https://null.co.in/chapters

I have made some refactoring on your original PR:
https://github.com/null-open-security-community/swachalit/commit/2ab89f2cd4b4b4a4d99856b5ab6713e234cbb7d4

If you are happy with this, let us go ahead and close this issue.

If you think there are some changes, feel free to raise new PR linked to this issue.

**Comment by avinashupadhya99** [comment]
I think we can close it.

**Comment by abhisek** [comment]
This is live now.
