### ISSUE TITLE
Create Swagger UI & JSON For Swachalit v2 API

### ISSUE THREAD

**Issue by abhisek** [null-open-security-community/swachalit#38]
- [ ] Manually created Swagger YAML
- [ ] Automatically generate JSON as part of CI/CD build
- [ ] Swagger UI with JSON URL configured

Basically, we should end up with something like:

http://null.co.in/api-v2/swagger

This should render a Swagger UI with everything pre-configured to play with.

**Comment by abhisek** [comment]
Hi @madhuakula

Can you contribute a Swagger YAML? The new APIs are being developed. You can see the APIs in action in `test/integration/api_v2_test.rb`

We need the Swagger YAML in `docs/api_v2_swagger.yml`

**Comment by madhuakula** [comment]
Sure, I will do that. Thanks for assigning :)

**Comment by abhisek** [comment]
Lets hold on to this.

I was able to use `Grape` and `Grape-Swaggle-Rails` to auto generated Swagger documentation from API endpoints.

No need to manually write Swagger YAML/JSON for now.

**Comment by madhuakula** [comment]
Okay. Sure
