### ISSUE TITLE
Archiving Chapter

### ISSUE THREAD

**Issue by anantshri** [null-open-security-community/swachalit#39]
If the chapter is not active there should be an option to archive the chapter. We dont want to loose the data but we dont want it in the active list. 

there could be an option added to revive the chapter.

**Comment by abhisek** [comment]
Chapter already have an active field that can be turned off from `/admin` panel.

**Comment by abhisek** [comment]
@anantshri You can go ahead and set the `active` flag to `false` for inactive chapters.
