### ISSUE TITLE
Migrate File Uploads to AWS S3 Storage

### ISSUE THREAD

**Issue by abhisek** [null-open-security-community/swachalit#4]
File upload is implemented using `Carrierwave` Ruby gem. The uploaders are available in `app/uploaders`

Currently, the uploaders are configured to use local file storage for uploaded content. This needs to be changed to use `Fog` for uploaded content storage.

`Fog` in turn need to be configured to use AWS S3 backed storage. Even though we do not use any private content, signed URLs is required to prevent the need for public bucket config.

The link below is relevant to the feature required:
https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3

**Comment by smritigarg** [comment]
Can you please this assign this issue to me, I am working on same

**Comment by abhisek** [comment]
> Can you please this assign this issue to me, I am working on same

Assigned to you.
