### ISSUE TITLE
Allow Comments & Like/Dislike for Session

### ISSUE THREAD

**Issue by anantshri** [null-open-security-community/swachalit#42]
Can we enable some sort of comments likes dislikes option for session. 
I would preferably link it to logged in users to avoid fraud

**Comment by abhisek** [comment]
We can use this gem for like/dislike:
https://github.com/davidcelis/recommendable

**Comment by anirban-a** [comment]
@abhisek you can maybe assign it to me.

**Comment by abhisek** [comment]
Sounds good @anirban-a 

This needs to be implemented in a bit modular manner.

For example, this will be used only for `EventSession` model. But the same feature may be required against other models as well in future.

**Comment by abhisek** [comment]
Hey @anirban-a 

Any progress on this? Let me know if you need any assistance.

**Comment by anirban-a** [comment]
Hi Abhishek,

I think it will be better if you can assign it to someone else now as I am
relocating to new city and totally occupied with all that. I doubt I'll be
able to work on it soon.

Apologies for the delay, I hope you understand.

Thanks and Regards.

**Comment by abhisek** [comment]
No problem. Thanks @anirban-a

**Comment by avinashupadhya99** [comment]
@abhisek You can maybe assign this to me. I will work on it.

**Comment by abhisek** [comment]
Done @avinashupadhya99

**Comment by avinashupadhya99** [comment]
> We can use this gem for like/dislike:
> https://github.com/davidcelis/recommendable

Is it necessary to use a recommandation engine for like/dislike? A simple/dislike gem like [Acts As Votable](https://github.com/ryanto/acts_as_votable) can be used. This gem persists the data in the db unlike [Recommendable](https://github.com/davidcelis/recommendable) which uses `Redis`.

**Comment by abhisek** [comment]
Ok. Sounds good. Go ahead as you like.

**Comment by anantshri** [comment]
couple of points.
1. If you open free text comments we need moderation or an option for admin to delete comments in case its voilating community guidelines.

**Comment by abhisek** [comment]
Awesome work @avinashupadhya99 

I merged this. This will go to production soon.
