### ISSUE TITLE
Sessions Search more filter options

### ISSUE THREAD

**Issue by anantshri** [null-open-security-community/swachalit#55]
At this point https://null.co.in/event_sessions shows all sessions and we can search for keyword. we should also have options like show results only with resources marked in them.

**Comment by anantshri** [comment]
Inconsistent results. https://null.community/event_sessions?has_a_reference=1&q=android

**Comment by abhisek** [comment]
This issue is fixed and deployed. Can you test and close this issue if its working?

**Comment by anantshri** [comment]
Looks good now. thanks for the quick update.
