### ISSUE TITLE
Page which lists proposed sessions

### ISSUE THREAD

**Issue by swapneelp** [null-open-security-community/swachalit#62]
It has occurred in the recent past that I have submitted a topic to multiple chapters and after a few days, completely lost track about it. It will be great to have page which displays the proposed sessions including ,date and timestamp, topic, chapter.  

This will avoid unnecessary duplicate submissions to the chapters and also gives information to the speakers on the current state of their submissions.

**Comment by abhisek** [comment]
Good suggestion. I have implemented this, will be deployed in production during next release.

![Screenshot-2020-08-31-103556](https://user-images.githubusercontent.com/31844/91684951-8481f880-eb76-11ea-921f-8efa61a24a89.png)

**Comment by abhisek** [comment]
This is in production now.
