### ISSUE TITLE
Events Operation - Feature Enhencement

### ISSUE THREAD

**Issue by x30r** [null-open-security-community/swachalit#63]
It is not possible to delete an event. (We had a workshop fixed which is not possible now. For now, we have unpublished the event but there is still an entry under https://null.community/leads/events)

Ref: {Swachalith Event #720}

**Comment by abhisek** [comment]
Hi @x30r 

This is an intentional feature. We don't allow deleting events and sub-resoures currently as there are collaboration across multiple individua.

The expected way is to unpublish the event and set `[CANCELLED]` in title.
