### ISSUE TITLE
Chapter Event List Incorrect Ordering

### ISSUE THREAD

**Issue by anantshri** [null-open-security-community/swachalit#66]
https://null.community/chapters/10-bhopal on chapter page the event list should be by default ordered by date and then by other elements
this shows 2018 as last entry but effectively its 2020.

**Comment by abhisek** [comment]
@sunilkr Can you check this?

The order is correct at controller level but I guess JS DataTable is messing this up. Check `app/views/events/_list.html.erb`

**Comment by anantshri** [comment]
Another quick update needed not sure where to put it.

### before

![image](https://user-images.githubusercontent.com/236843/108069691-a79f5680-7089-11eb-9528-45758a0e9b44.png)

### Code Change
```
a.paginate_button {
    padding-left: 10px;
    cursor: pointer;
}
```

### After 

![image](https://user-images.githubusercontent.com/236843/108069628-98b8a400-7089-11eb-89a1-d40638365cf1.png)

**Comment by anantshri** [comment]
@sunilkr another thing for you to check and see where this goes.
