### ISSUE TITLE
HTTP 404 on glyphocons

### ISSUE THREAD

**Issue by sunilkr** [null-open-security-community/swachalit#7]
It seems there are some issues in asset compilation.
![null-co-in-glyphicons-404](https://user-images.githubusercontent.com/407194/58465421-4a48d080-8155-11e9-91e3-aeb0bd046d56.png)

**Comment by abhisek** [comment]
Issue not fixed. Will look at it.

**Comment by v1bh0r** [comment]
Hi, @abhisek, can you please share a .env file with RAILS_ENV=production? It's taking me a lot of time trying to figure out the missing pieces...

**Comment by abhisek** [comment]
Hi @v1bh0r 

Just use the `.env` sample from:
https://github.com/null-open-security-community/swachalit/blob/master/doc/developer-guide-docker-compose.md

Change `RAILS_ENV` to `production`. That should work.

**Comment by abhisek** [comment]
Set `STORAGE_PROVIDER_DISABLED=true` in `.env` when running with `RAILS_ENV=production` for local development.

**Comment by abhisek** [comment]
Turns out it was a fix to handle hardcoded paths in `application.css` properly with `asset_path` helper.

For this, I have to rename `application.css` to `application.css.erb` so that I can  use Rails helpers in CSS.

**Comment by abhisek** [comment]
Finally! Fixed.
