### ISSUE TITLE
Add a page for null Social Media Links to replace linktree

### ISSUE THREAD

**Issue by prashant3535** [null-open-security-community/swachalit#95]
Can we add a page for all null Social Media Links and replace linktree with it? 

Also, have the page directly accessible via url: null.community/socialmedia ?

Similarly, have specific redirects for social media:
e.g null.community/discord redirects to the null Discord invite link.

**Comment by anantshri** [comment]
Since we have linktree in sponsors lts keep it to that till sitation changes.

https://null.community/pages/6-sponsors
